### ISSUE TITLE
Hylar as a dependency of a strict-Node.js 13 application

### ISSUE THREAD

**Issue by StatelessCat** [ucbl/HyLAR-Reasoner#13]
Hi,
When adding Hylar@1.8.5 as a dependency for a project that requires Node.js 13 to run, I did not succeed in building its dependencies, using `npm` nor `yarn`.

The faulty "sqlite3" transitive dependency of your project (`multer@1.4.2 -> rdflib@0.17.1 -> rdfstore@0.9.17 -> sqlite3@3.1.13`) prevent it.

The workaround is obviously to install Hylar as Node.js 10, then to require it in Node.js 13, which works, but not optimal. Or just to expressly `--ignore-engine`s and runtimes checks in `npm` but it did not work for me (still a problem to build sqlite3).

What is your opinion on it? 
Is it possible to change `multer` as an optional dependency?
What I'm missing on this problem?

Thanks.

**Comment by mterdjimi** [comment]
Hello and thanks for raising this issue.
Since rdfstore is not maintained, I forked it to remove its vulnerabilities. This includes an upgrade of sqlite3 to its latest version. [HyLAR 1.10](https://github.com/ucbl/HyLAR-Reasoner/releases/tag/v1.10.0) now uses this forked rdfstore package, which potentially solves problems with Node 13.

Let me know if this new version works on your side. If multer still causes dysfunctionsn, it should be solved in the next HyLAR release.

MT
