### ISSUE TITLE
not working with node8

### ISSUE THREAD

**Issue by KunalSaini** [ucbl/HyLAR-Reasoner#4]
Hi ,
I am installing this package in my application with ```npm install --save hylar``` and getting following error.
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  contextify.cc
  win_delay_load_hook.cc
..\src\contextify.cc(150): error C2039: 'SetAccessCheckCallbacks': is not a member of 'v8::ObjectTemplate' [C:\Us ers\csainik\proj\g4\algo-crosshairs\node_modules\contextify\build\contextify.vcxproj]
```

my environment details are as follows 
OS- window 7
and
```
node --version
v8.0.0
```
and 
```
npm --version
5.0.0
```

**Comment by Spadon** [comment]
Hello,

As far as I know, this issue is only solved by downgrading node version before 7 (6.9 works). cf. https://github.com/brianmcd/contextify/issues/205 (issue identified on OSX but similar to others known on Win7-8-10).
This is caused by some dependencies of rdfstore (including contextify and its own subdependencies) and unfortunately, this is the only workaround I know.
 
Still, seems that this issue can be solved by upgrading jsdom directly from rdfstore's dependencies, but I did not try this. I will try to give more information on this problem in the future, as you are not the only one facing this issue.

Thanks for your comment,

Mehdi.

**Comment by KunalSaini** [comment]
I tried to update rdfstore dependency here and also added lock file for node8 , please have a look at https://github.com/ucbl/HyLAR-Reasoner/pull/5

**Comment by Spadon** [comment]
Juste in case, try this command (in a Powershell prompt with admin rights)
`npm install --global --production windows-build-tools`
Does it solve your issue?

**Comment by Spadon** [comment]
Does

**Comment by MadsHolten** [comment]
Will this be solved?

**Comment by mterdjimi** [comment]
To solve this issue, I need to replace the current triplestore - rdfstore - by rdflib. As both implementations have different signatures, it may take a while.
Moreover, rdflib SPARQL support is currently a subset of what offers rdfstore; this implies functional regressions.

**Comment by MadsHolten** [comment]
I see. rdfstore also doesn't support OPTIONAL and MINUS statements which is quite a shame. In general, I think it is a shame that there are no libraries for JS that supports full SPARQL.

**Comment by mterdjimi** [comment]
I published a new release, which may solve the problem (upgraded some packages, including rdfstore itself, and removed some unused ones).

Can you tell me if it works for you?

Thanks.
